<?php

namespace Admin\ClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DBRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DBRoleRepository extends EntityRepository
{
}
