admin_catalog:
    resource: "@AdminCatalogBundle/Resources/config/routing.yml"
    prefix:   /

#api_data:
#    resource: "@APIDataBundle/Resources/config/routing.yml"
#    prefix:   /
#
#admin_data:
#    resource: "@AdminDataBundle/Resources/config/routing.yml"
#    prefix:   /
#
admin_client:
    resource: "@AdminClientBundle/Resources/config/routing.yml"
    prefix:   /

admin_language:
    resource: "@AdminLanguageBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:  /{_locale}/login
    defaults: { _controller: AdminClientBundle:Auth:index }

login_check:
    path:   /login_check

logout:
    path: /logout

contact_form:
    path:  /{_locale}/contact
    defaults: { _controller: AdminClientBundle:Contact:contact }