<?php

namespace Admin\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubstrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstrateRepository extends EntityRepository
{
}
