<?php

namespace Admin\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VerminCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerminCategoryRepository extends EntityRepository
{
}
