parameters:
#    admin_client.example.class: Admin\ClientBundle\Example

services:
#    admin_client.example:
#        class: %admin_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
